# This file is automatically generated.

cask "f0nt-abc-aschariya" do
    version "1.0"
  
    url "https://www.f0nt.com/download/ABCFont/ABC-Aschariya.zip"
    sha256 "6d10ce0be0f0ec8f20601c774185683c411abbb61396986bf150cb3769089c92"

    name "#ABC-Aschariya (#เอบีซี-อัจฉริยะ)"
    homepage "https://www.f0nt.com/release/abc-aschariya/"

    font "#ABC-ASCHARIYA.TTF"
 end