# This file is automatically generated.

cask "f0nt-sov-patavi" do
    version "1.0"
  
    url "https://www.f0nt.com/download/uvSOV/SOV_patavi.zip"
    sha256 "61d0aec5ac80f0dd0e8b7c526699a2f9f6a3080d908c070df6e37daf25443d1f"

    name "ปฐวี (SOV_patavi)"
    homepage "https://www.f0nt.com/release/sov-patavi/"

    font "SOV_patavi/SOV_Patavi.ttf"
 end