# This file is automatically generated.

cask "f0nt-edpoonpunn" do
    version "1.0"
  
    url "https://www.f0nt.com/download/edcrub/EDPoonPunn.ttf.zip"
    sha256 "dfa1c130c1abbecd420f100840e61bad9d4f8ae9644614f8c5c06d7f0aceb70d"

    name "EDPoonPunn (ปูนปั้น)"
    homepage "https://www.f0nt.com/release/edpoonpunn/"

    font "EDPoonPunn.ttf"
 end