# This file is automatically generated.

cask "f0nt-sov-baanhook" do
    version "1.0"
  
    url "https://www.f0nt.com/download/uvSOV/SOV_BaanHook.zip"
    sha256 "58d4cba3b1b70779c571ec9b929b99634ecf8148235dcc6adb7f84dac6f221b3"

    name "บ้านฮูก (Sov_BaanHook)"
    homepage "https://www.f0nt.com/release/sov-baanhook/"

    font "SOV_BaanHook/SOV_BaanHook.ttf"
 end