# This file is automatically generated.

cask "f0nt-sov-naiklong" do
    version "1.0"
  
    url "https://www.f0nt.com/download/uvSOV/SOV_NaiKlong.zip"
    sha256 "06c025b65dcfd15260dab911d0e01a762f3f6b7d15812d0ee17a137d14e5d4e3"

    name "ในกล่อง (SOV_naiklong)"
    homepage "https://www.f0nt.com/release/sov-naiklong/"

    font "SOV_NaiKlong/SOV_NaiKlong.ttf"
 end