# This file is automatically generated.

cask "f0nt-sov-apo" do
    version "1.0"
  
    url "https://www.f0nt.com/download/uvSOV/SOV_apo.zip"
    sha256 "89bf693c1478870ae77b71617c8c599b555351da183f93edf3caea669169c4bd"

    name "อาโป (SOV_apo)"
    homepage "https://www.f0nt.com/release/sov-apo/"

    font "SOV_apo/SOV_Apo-Bold.ttf"
    font "SOV_apo/SOV_Apo.ttf"
 end