# This file is automatically generated.

cask "f0nt-sov-tejo" do
    version "1.0"
  
    url "https://www.f0nt.com/download/uvSOV/SOV_tejo.zip"
    sha256 "201df664f4fd15caad8d26ea6415b68b75a25f21b3bb3f2dff516d395fec21d7"

    name "เตโช (SOV_tejo)"
    homepage "https://www.f0nt.com/release/sov-tejo/"

    font "SOV_tejo/SOV_Tejo.ttf"
 end