# This file is automatically generated.

cask "f0nt-sd-prostreet" do
    version "1.0"
  
    url "https://www.f0nt.com/download/siinsticker123/sd-prostreet.zip"
    sha256 "7d1947dc5eadaa01d67fc389d171df05dd28ce87669e1c1055dd9bcd0a910b66"

    name "เอสดี โปรสตรีท (sd prostreet)"
    homepage "https://www.f0nt.com/release/sd-prostreet/"

    font "sd prostreet 2.ttf"
 end