# This file is automatically generated.

cask "f0nt-uid-salmon-2019" do
    version "1.0"
  
    url "https://www.f0nt.com/download/UIDFONT/UID-SALMON-2019.zip"
    sha256 "3ec3b96e4657949e7d101cf17227b6b7d5b0fdd5189eb9063ee46fe408cfd696"

    name "UID SALMON 2019"
    homepage "https://www.f0nt.com/release/uid-salmon-2019/"

    font "UID SALMON 2019 .ttf"
    font "__MACOSX/._UID SALMON 2019 .ttf"
 end