# This file is automatically generated.

cask "font-f0nt-arabica" do
    version "1"
  
    url "https://www.f0nt.com/download/superstore/Arabica.zip"
    sha256 "ed9508f839a19ebe98b92d99665b07122f68f54f7285a22b5c118e75b0e1028a"

    name "Arabica"
    homepage "https://www.f0nt.com/release/arabica/"

    font "Arabica file/ttf/Arabica-Italic.ttf"
    font "__MACOSX/Arabica file/ttf/._Arabica-Italic.ttf"
    font "Arabica file/ttf/Arabica.ttf"
    font "__MACOSX/Arabica file/ttf/._Arabica.ttf"
 end