# This file is automatically generated.

cask "font-f0nt-ts-som-tum-np" do
    version "1"
  
    url "https://www.f0nt.com/download/tsfont/TS-SOM-TUM-NP.zip"
    sha256 "78125e1cc33de73bef3cbedd81ef2f57d88ce97993e58738ae943010191dd44c"

    name "TS-SOM TUM-NP (ส้มตำ)"
    homepage "https://www.f0nt.com/release/ts-som-tum-np/"

    font "TS-SOM TUM-NP/TS-Som tum -A Italic -NP.ttf"
    font "TS-SOM TUM-NP/TS-Som tum -A Shadow Italic-NP.ttf"
    font "TS-SOM TUM-NP/TS-Som tum -A Shadow-NP.ttf"
    font "TS-SOM TUM-NP/TS-Som tum -A-NP.ttf"
    font "TS-SOM TUM-NP/TS-Som tum -B Shadow-NP.ttf"
    font "TS-SOM TUM-NP/TS-Som tum-B-NP.ttf"
    font "TS-SOM TUM-NP/TS-SOM TUM-np.ttf"
    font "TS-SOM TUM-NP/TS-SOM TUM-Shadow-np.ttf"
 end