# This file is automatically generated.

cask "font-f0nt-kutlaimuu" do
    version "1"
  
    url "https://www.f0nt.com/download/layiji/Layiji_kutlaimuu.zip"
    sha256 "ded7aadf420ad481894011878155b6d93eb259c4686d35a94b3af5803749b4c8"

    name "Layiji คัดลายมือ"
    homepage "https://www.f0nt.com/release/layiji-%e0%b8%84%e0%b8%b1%e0%b8%94%e0%b8%a5%e0%b8%b2%e0%b8%a2%e0%b8%a1%e0%b8%b7%e0%b8%ad/"

    font "Layiji_kutlaimuu.ttf"
 end