# This file is automatically generated.

cask "font-f0nt-bangnumpueng" do
    version "1"
  
    url "https://www.f0nt.com/download/maiippg/Bangnumpueng.zip"
    sha256 "2cb9d2a471bf585a2f376dcdf3530aaab204f67e015314e79c0f0329f3ccbb61"

    name "Bangnumpueng (บางน้ำผึ้ง)"
    homepage "https://www.f0nt.com/release/bangnumpueng/"

    font "Bangnumpueng/Bangnampueng.ttf"
 end