# This file is automatically generated.

cask "font-f0nt-atnoon" do
    version "1"
  
    url "https://www.f0nt.com/download/atnoon/atnoon_regular.zip"
    sha256 "c66a6d440e889a79886e6b7e961bb87c5103ebe018d54aa328149af2f944e6f7"

    name "4711_AtNoon_Regular"
    homepage "https://www.f0nt.com/release/4711_atnoon_regular/"

    font "4711_AtNoon_Regular.ttf"
 end