# This file is automatically generated.

cask "font-f0nt-saruns-manorah" do
    version "1"
  
    url "https://www.f0nt.com/download/sarun29/SarunsManorah.zip"
    sha256 "59c82fcd43a0ac5be31cbfa5a8719eee0d8a87325428a01ad05973b6fe93a735"

    name "Sarun\’s Manorah"
    homepage "https://www.f0nt.com/release/saruns-manorah/"

    font "Sarun's Manorah.ttf"
 end