# This file is automatically generated.

cask "font-f0nt-layiji-mahaniyom-bao-1-2" do
    version "1"
  
    url "https://www.f0nt.com/download/layiji/LayijiMahaniyom-Bao-1.2.zip"
    sha256 "6187c9e4aa39c30c409aedd2b2ee137992f017b9790576b7c78909ff5bcbccfe"

    name "Layiji มหานิยม เบา 1.2"
    homepage "https://www.f0nt.com/release/layiji-mahaniyom-bao-1-2/"

    font "LayijiMahaniyom-Bao-1.2.ttf"
 end