# This file is automatically generated.

cask "font-f0nt-salmah-teen" do
    version "1"
  
    url "https://www.f0nt.com/download/salamah27/Salmah_Teen.zip"
    sha256 "d9ce2914e101e5a68ba4999c9fdbc560d045814e937ab32474c8678b3d1ffda3"

    name "Salmah_Teen"
    homepage "https://www.f0nt.com/release/salmah_teen/"

    font "Salmah_Teen.ttf"
 end