cask 'f0nt-collection-sipa' do
    version '1.0'
  
    url "https://storage.googleapis.com/codeforthailand/13-thai-national-fonts-#{version}.zip"
    sha256 "1870d5982bbbbedc63253b8fb6ae0cd17247fef331ab397bd1347a610a2bbac9"
    name "13 Thai National Fonts by SIPA"
    homepage "https://www.nstda.or.th/th/news/12102-thai-font"

    font "TH Baijam Bold Italic.ttf"
    font "TH Baijam Bold.ttf"
    font "TH Baijam Italic.ttf"
    font "TH Baijam.ttf"
    font "TH Chakra Petch Bold Italic.ttf"
    font "TH Chakra Petch Bold.ttf"
    font "TH Chakra Petch Italic.ttf"
    font "TH Chakra Petch.ttf"
    font "TH Charm of AU.ttf"
    font "TH Charmonman Bold.ttf"
    font "TH Charmonman.ttf"
    font "TH Fahkwang Bold Italic.ttf"
    font "TH Fahkwang Bold.ttf"
    font "TH Fahkwang Italic.ttf"
    font "TH Fahkwang.ttf"
    font "TH K2D July8 Bold Italic.ttf"
    font "TH K2D July8 Bold.ttf"
    font "TH K2D July8 Italic.ttf"
    font "TH K2D July8.ttf"
    font "TH KoHo Bold Italic.ttf"
    font "TH KoHo Bold.ttf"
    font "TH KoHo Italic.ttf"
    font "TH KoHo.ttf"
    font "TH Kodchasal Bold Italic.ttf"
    font "TH Kodchasal Bold.ttf"
    font "TH Kodchasal Italic.ttf"
    font "TH Kodchasal.ttf"
    font "TH Krub Bold Italic.ttf"
    font "TH Krub Bold.ttf"
    font "TH Krub Italic.ttf"
    font "TH Krub.ttf"
    font "TH Mali Grade6 Bold Italic.ttf"
    font "TH Mali Grade6 Bold.ttf"
    font "TH Mali Grade6 Italic.ttf"
    font "TH Mali Grade6.ttf"
    font "TH Niramit AS Bold Italic.ttf"
    font "TH Niramit AS Bold.ttf"
    font "TH Niramit AS Italic.ttf"
    font "TH Niramit AS.ttf"
    font "TH Srisakdi Bold.ttf"
    font "TH Srisakdi.ttf"
    font "THSarabun Bold.ttf"
    font "THSarabun BoldItalic.ttf"
    font "THSarabun Italic.ttf"
    font "THSarabun.ttf"
    font "THSarabunNew Bold.ttf"
    font "THSarabunNew BoldItalic.ttf"
    font "THSarabunNew Italic.ttf"
    font "THSarabunNew.ttf"
 end