# This file is automatically generated.

cask "font-f0nt-blk-bangli-ko-sa-na" do
    version "1"
  
    url "https://www.f0nt.com/download/bangli-ko-sa-na/BLK-BangLi-Ko-Sa-Na.zip"
    sha256 "326b938ff687a05f775ba5410b478d821ce3bd0f5f3fb7c5fd269570a4c45e63"

    name "BLK-BangLi-Ko-Sa-Na"
    homepage "https://www.f0nt.com/release/blk-bangli-ko-sa-na/"

    font "BLK-BangLi-Ko-Sa-Na.ttf"
 end