# This file is automatically generated.

cask "font-f0nt-tlu-huatoo0" do
    version "1"
  
    url "https://www.f0nt.com/download/thelittleuki/5012_tLU_huatoo0.zip"
    sha256 "fc5df6759a3195a49059f3cf1d6702aebaa7f5b38586bbc7f9c1b3b0070a9201"

    name "5012_tLU_huatoo0"
    homepage "https://www.f0nt.com/release/5012_tlu_huatoo0/"

    font "5012_tLU_huatoo0.ttf"
    font "5012_tLU_huatoo0_BOLD.ttf"
 end