# This file is automatically generated.

cask "font-f0nt-circular-2" do
    version "1"
  
    url "https://www.f0nt.com/download/tiraw/Circular2.zip"
    sha256 "632e8dce190540611411f232cbecad2995298395ce4b5b6b93d48e32a8a525f0"

    name "Circular"
    homepage "https://www.f0nt.com/release/circular-2/"

    font "Circular.ttf"
    font "CircularBold.ttf"
 end