# This file is automatically generated.

cask "font-collection-f0nt" do
    version "1.0"
  
    url "https://storage.googleapis.com/codeforthailand/fonts/collection-f0nt-top-20.zip"
    sha256 "1f180840c311ea000e2619c7ce06d98d22344b0c93a70ddc7c5f4459574c7c4f"

    name "Top 20 Fonts from f0nt.com"
    homepage "https://www.f0nt.com"

        depends_on cask: "font-f0nt-atnoon-bighead"
        depends_on cask: "font-f0nt-waffle"
        depends_on cask: "font-f0nt-sanamdeklen-chaya"
        depends_on cask: "font-f0nt-tlu-huatoo0"
        depends_on cask: "font-f0nt-supermarket"
        depends_on cask: "font-f0nt-iannnnnmtv"
        depends_on cask: "font-f0nt-tlu-jiumjium"
        depends_on cask: "font-f0nt-layiji-sarangheyo"
        depends_on cask: "font-f0nt-rukdeaw"
        depends_on cask: "font-f0nt-pahnto"
        depends_on cask: "font-f0nt-bangnumpueng"
        depends_on cask: "font-f0nt-atnoon"
        depends_on cask: "font-f0nt-nongaor"
        depends_on cask: "font-f0nt-book-r-lux-2006"
        depends_on cask: "font-f0nt-layiji-mahaniyom-bao-1-2"
        depends_on cask: "font-f0nt-bangna-new"
        depends_on cask: "font-f0nt-iannnnnjpg"
        depends_on cask: "font-f0nt-saruns-manorah"
        depends_on cask: "font-f0nt-arabica"
        depends_on cask: "font-f0nt-lzk03-b2campus"
        depends_on cask: "font-f0nt-blk-bangli-ko-sa-na"
        depends_on cask: "font-f0nt-kruengprung"
 end