cask 'font-collection-tepc' do
    version '1.0'

    url "https://storage.googleapis.com/codeforthailand/fonts/tepc-#{version}.zip"
    sha256 "55892ac87613da3397c5d35774dc98711b5187b8f5a159b0c0c1d3947c8583e1"
    name "This font program is the property of Thai Electronic Publishing Club (TEPC). It is distributed as copyrighted freeware. You may use this font program without any charge and may distribute it, as is, to others only if the complete font archive remains unchanged and all files are distributed together."
    homepage "http://www.tepclub.club"

    font "./tepc/Aksaramatee-Bold-Italic.ttf"
    font "./tepc/Aksaramatee-Bold.ttf"
    font "./tepc/Aksaramatee-Italic.ttf"
    font "./tepc/Aksaramatee-Regular.ttf"
    font "./tepc/ChulaNarak-Bold-Italic.ttf"
    font "./tepc/ChulaNarak-Bold.ttf"
    font "./tepc/ChulaNarak-Italic.ttf"
    font "./tepc/ChulaNarak-Regular.ttf"
    font "./tepc/CmPrasanmit-Bold-Italic.ttf"
    font "./tepc/CmPrasanmit-Bold.ttf"
    font "./tepc/CmPrasanmit-Italic.ttf"
    font "./tepc/CmPrasanmit-Regular.ttf"
    font "./tepc/DC-Palamongkol-Bold-Italic.ttf"
    font "./tepc/DC-Palamongkol-Bold.ttf"
    font "./tepc/DC-Palamongkol-Italic.ttf"
    font "./tepc/DC-Palamongkol-Regular.ttf"
    font "./tepc/FonLeb-Bold-Italic.ttf"
    font "./tepc/FonLeb-Bold.ttf"
    font "./tepc/FonLeb-Italic.ttf"
    font "./tepc/FonLeb-Regular.ttf"
    font "./tepc/Himmaparnt-Bold-Italic.ttf"
    font "./tepc/Himmaparnt-Bold.ttf"
    font "./tepc/Himmaparnt-Italic.ttf"
    font "./tepc/Himmaparnt-Regular.ttf"
    font "./tepc/KaniGa-Bold-Italic.ttf"
    font "./tepc/KaniGa-Bold.ttf"
    font "./tepc/KaniGa-Italic.ttf"
    font "./tepc/KaniGa-Regular.ttf"
    font "./tepc/Nakaracha-Bold-Italic.ttf"
    font "./tepc/Nakaracha-Bold.ttf"
    font "./tepc/Nakaracha-Italic.ttf"
    font "./tepc/Nakaracha-Regular.ttf"
    font "./tepc/PSK-Smart-Bold.ttf"
    font "./tepc/PSK-Smart-Regular.ttf"
    font "./tepc/PSK-SmartBI.ttf"
    font "./tepc/PSK-SmartItaic.ttf"
    font "./tepc/SR-FahMai-Bold-Italic.ttf"
    font "./tepc/SR-FahMai-Bold.ttf"
    font "./tepc/SR-FahMai-Italic.ttf"
    font "./tepc/SR-FahMai-Normal.ttf"
end