# This file is automatically generated.

cask "font-f0nt-iannnnngmo" do
    version "1"
  
    url "https://www.f0nt.com/download/iannnnn/2005_iannnnnGMO.zip"
    sha256 "bc26a3063b1669091c17f7732671b2312e040c4d3e7100c2d5f6dc5eead63545"

    name "iannnnnGMO (2005)"
    homepage "https://www.f0nt.com/release/iannnnngmo/"

    font "2005_iannnnnGMO.ttf"
 end