# This file is automatically generated.

cask "font-f0nt-ah-lugdek" do
    version "1"
  
    url "https://www.f0nt.com/download/phukradung/ah_lugdek.zip"
    sha256 "c48d864bcf5dcf7804b02df1b5ed6784ce5bfd22ce1af4a95a34398829cf703a"

    name "AH_LuGDeK"
    homepage "https://www.f0nt.com/release/ah_lugdek/"

    font "AH_LuGDeK.ttf"
 end