# This file is automatically generated.

cask "font-f0nt-torsilp-gimchi" do
    version "1"
  
    url "https://www.f0nt.com/download/rajun/torsilp-gimchi.zip"
    sha256 "113bad6c206737e720f1d2740546e68109474ed4824e03c2001299b3ab0a0896"

    name "torsilp-gimchi"
    homepage "https://www.f0nt.com/release/torsilp-gimchi/"

    font "torsilp-gimchi/torsilp-gimchi.ttf"
 end