# This file is automatically generated.

cask "font-f0nt-lzk03-b2campus" do
    version "1"
  
    url "https://www.f0nt.com/download/thelazykiller/lzk03_b2campus.zip"
    sha256 "790b729a41c9045890e3d13f1c4e5e623ecda45ee87fd60510342560c3fb6e96"

    name "Lzk03_b2campus"
    homepage "https://www.f0nt.com/release/lzk03_b2campus/"

    font "Lzk03_b2campus.ttf"
 end