# This file is automatically generated.

cask "font-f0nt-lomoor" do
    version "1"
  
    url "https://www.f0nt.com/download/mr-bo41/Lomoor-Renew.zip"
    sha256 "1c9631edf52527a6702305c0e107efe4f2e1f5a5acb3d2c0b340411aae920003"

    name "โลมัว (Lomoor)"
    homepage "https://www.f0nt.com/release/lomoor/"

    font "Lomoor-Renew.ttf"
 end