# This file is automatically generated.

cask "font-f0nt-kunlasatri" do
    version "1"
  
    url "https://www.f0nt.com/download/superstore/Kunlasatri.zip"
    sha256 "babe5d0df0c5b930cc710941dfaeb64bd563cbe08ad6e16cb15c798895de1098"

    name "กุลสตรี"
    homepage "https://www.f0nt.com/release/kunlasatri/"

    font "Kunlasatri/Kunlasatri-Bold.ttf"
    font "Kunlasatri/Kunlasatri-Light.ttf"
    font "Kunlasatri/Kunlasatri.ttf"
 end