# This file is automatically generated.

cask "font-f0nt-jaew" do
    version "1"
  
    url "https://www.f0nt.com/download/candit39/can_Jaew.zip"
    sha256 "098302ad55b727171a1cc6492ef16610e24b6cda4ae9542f5ed7337989adadc8"

    name "แจ๋ว (can_Jaew)"
    homepage "https://www.f0nt.com/release/แจ๋ว-can_jaew/"

    font "can_Jaew/can_Jaew.ttf"
 end