# This file is automatically generated.

cask "font-f0nt-rukdeaw" do
    version "1"
  
    url "https://www.f0nt.com/download/candit39/Can_Rukdeaw.zip"
    sha256 "f2e89120a01209f191134aaaa55860eb2dc724cb9f13489e3bcbd5b7f3128e83"

    name "รักเดียว (can_Rukdeaw)"
    homepage "https://www.f0nt.com/release/รักเดียว-can_rukdeaw/"

    font "can_Rukdeaw01.ttf"
 end