# This file is automatically generated.

cask "font-f0nt-the-little-uki-noworry" do
    version "1"
  
    url "https://www.f0nt.com/download/thelittleuki/5011_thE_Little_Uki_noworry.zip"
    sha256 "61acefcc7f335433eb70bdfc0d154c5fec658705f72dee0264fd71ee61afd36c"

    name "5011_thE_Little_Uki_noworry"
    homepage "https://www.f0nt.com/release/5011_the_little_uki_noworry/"

    font "5011_thE_Little_Uki_noworry.ttf"
 end