# This file is automatically generated.

cask "font-f0nt-little-star-0406" do
    version "1"
  
    url "https://www.f0nt.com/download/noname/Little_Star_0406.zip"
    sha256 "07fca1dad3a95e6c787ff200459d773f941980067097b590d7bb89a24c648d4b"

    name "Little_Star_0406"
    homepage "https://www.f0nt.com/release/little_star_0406/"

    font "Little_Star_0406.ttf"
 end