# This file is automatically generated.

cask "font-f0nt-atnoon-bighead" do
    version "1"
  
    url "https://www.f0nt.com/download/atnoon/atnoon_bighead.zip"
    sha256 "52187a6cbedae4f40dbe0c518ff161bf78b4a0953b456a36337bd42d4d2a6846"

    name "4711_AtNoon_BigHead"
    homepage "https://www.f0nt.com/release/4711_atnoon_bighead/"

    font "4711_AtNoon_BigHead.ttf"
 end