# This file is automatically generated.

cask "font-f0nt-pahnto" do
    version "1"
  
    url "https://www.f0nt.com/download/pahn/pahnto.zip"
    sha256 "c41dc331f39206c4dcbb43471e533e305a4a2a05b4e7453783aca9adcd027e8d"

    name "Pahnto"
    homepage "https://www.f0nt.com/release/pahnto/"

    font "pahnto.ttf"
 end