# This file is automatically generated.

cask "font-f0nt-iannnnnbkk" do
    version "1"
  
    url "https://www.f0nt.com/download/iannnnn/2006_iannnnnBKK.zip"
    sha256 "3cbcfc07f9779e9816104197325388fa178c1a02ea162266abb04dfacfe17dd6"

    name "iannnnnBKK (2006)"
    homepage "https://www.f0nt.com/release/iannnnnbkk/"

    font "2006_iannnnnBKK.ttf"
 end