# This file is automatically generated.

cask "font-f0nt-superspace" do
    version "1"
  
    url "https://www.f0nt.com/download/fontcraft/Superspace.zip"
    sha256 "77747d286a4dc7961421f355b99d175f80c3a42c1eb3c27ee3c763aa8ad71685"

    name "ซุปเปอร์สเปซ (Superspace)"
    homepage "https://www.f0nt.com/release/superspace/"

    font "Superspace Bold Italic ver 1.00.ttf"
    font "__MACOSX/._Superspace Bold Italic ver 1.00.ttf"
    font "Superspace Bold Slant ver 1.00.ttf"
    font "__MACOSX/._Superspace Bold Slant ver 1.00.ttf"
    font "Superspace Bold ver 1.00.ttf"
    font "__MACOSX/._Superspace Bold ver 1.00.ttf"
    font "Superspace Light Italic ver 1.00.ttf"
    font "__MACOSX/._Superspace Light Italic ver 1.00.ttf"
    font "Superspace Light Slant ver 1.00.ttf"
    font "__MACOSX/._Superspace Light Slant ver 1.00.ttf"
    font "Superspace Light ver 1.00.ttf"
    font "__MACOSX/._Superspace Light ver 1.00.ttf"
    font "Superspace Regular Italic ver 1.00.ttf"
    font "__MACOSX/._Superspace Regular Italic ver 1.00.ttf"
    font "Superspace Regular ver 1.00 Slant.ttf"
    font "__MACOSX/._Superspace Regular ver 1.00 Slant.ttf"
    font "Superspace Regular ver 1.00.ttf"
    font "__MACOSX/._Superspace Regular ver 1.00.ttf"
 end