# This file is automatically generated.

cask "font-f0nt-saruns-harrypotter" do
    version "1"
  
    url "https://www.f0nt.com/download/sarun29/sarun_hp.zip"
    sha256 "ca5c274b634983ca2d3072861334deff2dfddcd1866128d56313a83b936b20b6"

    name "Sarun\’s HarryPotter"
    homepage "https://www.f0nt.com/release/saruns-harrypotter/"

    font "Sarun's HarryPotter.ttf"
 end