# This file is automatically generated.

cask "font-f0nt-kt-smarn-seree" do
    version "1"
  
    url "https://www.f0nt.com/download/smarnfont/kt_smarn-seree.zip"
    sha256 "30605c9f8fe723c805a07ca1fc04fad19bde0836762db273ddf58ef26265a99a"

    name "kt_smarn seree"
    homepage "https://www.f0nt.com/release/kt_smarn-seree/"

    font "kt_smarn seree.ttf"
 end