# This file is automatically generated.

cask "font-f0nt-iannnnnjpg" do
    version "1"
  
    url "https://www.f0nt.com/download/iannnnn/2005_iannnnnJPG.zip"
    sha256 "528a6365ea6ba3baa7bfa3db84ac8293a39abdbaa8e3b1dfd914a795dbe3287d"

    name "iannnnnJPG (2005)"
    homepage "https://www.f0nt.com/release/iannnnnjpg/"

    font "2005_iannnnnJPG.ttf"
 end