# This file is automatically generated.

cask "font-f0nt-anchan" do
    version "1"
  
    url "https://www.f0nt.com/download/zilch/Anchan.zip"
    sha256 "5534a51140446cec15d608cc533c305a535797a85d00a3de9c1612b421f75445"

    name "อัญชัน (Anchan)"
    homepage "https://www.f0nt.com/release/anchan/"

    font "Anchan.ttf"
 end