# This file is automatically generated.

cask "font-f0nt-nongaor" do
    version "1"
  
    url "https://www.f0nt.com/download/candit39/can_NongAor.zip"
    sha256 "a1e21d67a4ef6f71efb8cf843a3a7cd8fd12856e32079473a9ff50378afcdddd"

    name "น้องอ้อ (can_NongAor)"
    homepage "https://www.f0nt.com/release/can_nongaor/"

    font "can_NongAor.ttf"
 end