# This file is automatically generated.

cask "font-f0nt-death-note" do
    version "1"
  
    url "https://www.f0nt.com/download/chaotoo/05_zz_deathnote.zip"
    sha256 "e413e4309db8f70cbe356f25f8c943c638eb4d78529d51fc5a1af0a4085c58b5"

    name "05_ZZ Death Note"
    homepage "https://www.f0nt.com/release/05_zz-death-note/"

    font "05_zz_deathnote/05_ZZ Death Note 1.0.ttf"
 end