# This file is automatically generated.

cask "font-f0nt-kruengprung" do
    version "1"
  
    url "https://www.f0nt.com/download/superstore/kruengprung.zip"
    sha256 "c1ce57f1d19fbf62650501699f1b93b1a36c36389ecc3bfdc829f650e0093e3f"

    name "Kruengprung / เครื่องปรุง"
    homepage "https://www.f0nt.com/release/kruengprung/"

    font "kruengprung/kruengprung-Italic.ttf"
    font "kruengprung/kruengprung.ttf"
 end