# This file is automatically generated.

cask "font-f0nt-sanamdeklen-chaya" do
    version "1"
  
    url "https://www.f0nt.com/download/chaya/SanamDeklen_chaya.zip"
    sha256 "d20712611a5fa3ab1522cdef7d15c0516d10505246eefa0832f14553a161eeb1"

    name "สนามเด็กเล่น | SanamDeklen_chaya"
    homepage "https://www.f0nt.com/release/sanamdeklen-chaya/"

    font "SanamDeklen_chaya/SanamDeklen_chaya.ttf"
 end