# This file is automatically generated.

cask "font-f0nt-tlu-jiumjium" do
    version "1"
  
    url "https://www.f0nt.com/download/thelittleuki/5103_tLU_JIUMJIUM.zip"
    sha256 "d2136b6dcec9275f0e8a4e81bdf70143d2c5750fc798681f795dcc101dc13aab"

    name "5103_TLU_JIUMJIUM"
    homepage "https://www.f0nt.com/release/5103_tlu_jiumjium/"

    font "5103_tLU_JIUMJIUM.ttf"
 end