# This file is automatically generated.

cask "font-f0nt-waffle" do
    version "1"
  
    url "https://www.f0nt.com/download/fontcraft/Waffle-Font.zip"
    sha256 "d62d61e054a0ebb56bc78382d67600172f4759c73cfbb0c11115f1bf3c41f249"

    name "Waffle"
    homepage "https://www.f0nt.com/release/waffle/"

 end