# This file is automatically generated.

cask "font-f0nt-little-star-0506" do
    version "1"
  
    url "https://www.f0nt.com/download/noname/Little_Star_0506.zip"
    sha256 "15f00e19530b62a51bfed5c7ebe296457de3d6d794ae62888f575f85fee5bb1b"

    name "Little_Star_0506"
    homepage "https://www.f0nt.com/release/little_star_0506/"

    font "Little_Stat_0506.ttf"
 end