# This file is automatically generated.

cask "font-f0nt-layiji-ruduuron" do
    version "1"
  
    url "https://www.f0nt.com/download/layiji/Layiji-RuDuuRon.zip"
    sha256 "4c6b297da735f271a41d74b4913f76fca3edc2e5bd7eadbc2df13413b72a81c1"

    name "Layiji ฤดูร้อน"
    homepage "https://www.f0nt.com/release/layiji-ruduuron/"

    font "Layiji RuDuuRon Mak.ttf"
    font "Layiji RuDuuRon Yaow.ttf"
    font "Layiji RuDuuRon YaowMak.ttf"
    font "Layiji RuDuuRon.ttf"
 end