# This file is automatically generated.

cask "font-f0nt-saruns-bang_rajan" do
    version "1"
  
    url "https://www.f0nt.com/download/sarun29/Saruns_Bang_rajan.zip"
    sha256 "462f982370e32ff14a8ae6643e5472d399a113a3a1adc4a4ca565478f70f0fa2"

    name "Sarun\’s Bang_rajan"
    homepage "https://www.f0nt.com/release/saruns-bang_rajan/"

    font "Sarun's Bang_rajan.ttf"
 end