# This file is automatically generated.

cask "font-f0nt-supermarket" do
    version "1"
  
    url "https://www.f0nt.com/download/superstore/supermarket.zip"
    sha256 "3b49d766202474eef8f85679aa105da9e885d9e5f35edfb7d20d391e2e50f11c"

    name "ซูเปอร์มาร์เก็ต"
    homepage "https://www.f0nt.com/release/supermarket/"

    font "supermarket-1-1/supermarket.ttf"
    font "__MACOSX/supermarket-1-1/._supermarket.ttf"
 end