# This file is automatically generated.

cask "font-f0nt-peach-tv" do
    version "1"
  
    url "https://www.f0nt.com/download/peach/peach_tv.zip"
    sha256 "29b56e1a9bbeec6888107074201ad0b14976f1f9a9c18fb70b0c93b95c46bd54"

    name "Peach TV"
    homepage "https://www.f0nt.com/release/peach-tv/"

    font "Peach_TV.ttf"
 end