cask 'font-collection-nectec-tlwg' do
    version '1.0'

    url "https://storage.googleapis.com/codeforthailand/fonts/nectec-tlwg-#{version}.zip"
    sha256 "e5bdfeaf8bf3732802bc225c4a4c9a3d170f263091696fd473ec283b119576d6"
    name "NECTEC Thai National Fonts are open source and free. Some of these fonts have been modified (by font designers from the Thai Linux Working Group (TLWG), hence their dual-copyright nature."
    homepage "https://www.nectec.or.th/pub/review-software/font/national-fonts.html"

    font "./nectec-tlwg/Garuda-Bold-Oblique.ttf"
    font "./nectec-tlwg/Garuda-Bold.ttf"
    font "./nectec-tlwg/Garuda-Book.ttf"
    font "./nectec-tlwg/Garuda-Oblique.ttf"
    font "./nectec-tlwg/Kinnari-Bold-Italic.ttf"
    font "./nectec-tlwg/Kinnari-Bold-Oblique.ttf"
    font "./nectec-tlwg/Kinnari-Bold.ttf"
    font "./nectec-tlwg/Kinnari-Italic.ttf"
    font "./nectec-tlwg/Kinnari-Medium.ttf"
    font "./nectec-tlwg/Kinnari-Oblique.ttf"
    font "./nectec-tlwg/Loma-Bold-Oblique.ttf"
    font "./nectec-tlwg/Loma-Bold.ttf"
    font "./nectec-tlwg/Loma-Book.ttf"
    font "./nectec-tlwg/Loma-Oblique.ttf"
    font "./nectec-tlwg/Norasi-Bold-Italic.ttf"
    font "./nectec-tlwg/Norasi-Bold-Oblique.ttf"
    font "./nectec-tlwg/Norasi-Bold.ttf"
    font "./nectec-tlwg/Norasi-Italic.ttf"
    font "./nectec-tlwg/Norasi-Oblique.ttf"
    font "./nectec-tlwg/Norasi-Regular.ttf"
    font "./nectec-tlwg/Purisa-Bold-Oblique.ttf"
    font "./nectec-tlwg/Purisa-Bold.ttf"
    font "./nectec-tlwg/Purisa-Medium.ttf"
    font "./nectec-tlwg/Purisa-Oblique.ttf"
    font "./nectec-tlwg/TlwgTypewriter-Bold-Oblique.ttf"
    font "./nectec-tlwg/TlwgTypewriter-Bold.ttf"
    font "./nectec-tlwg/TlwgTypewriter-Medium.ttf"
    font "./nectec-tlwg/TlwgTypewriter-Oblique.ttf"
    font "./nectec-tlwg/TlwgTypo-Bold-Oblique.ttf"
    font "./nectec-tlwg/TlwgTypo-Bold.ttf"
    font "./nectec-tlwg/TlwgTypo-Medium.ttf"
    font "./nectec-tlwg/TlwgTypo-Oblique.ttf"
    font "./nectec-tlwg/Umpush-Bold-Oblique.ttf"
    font "./nectec-tlwg/Umpush-Bold.ttf"
    font "./nectec-tlwg/Umpush-Book.ttf"
    font "./nectec-tlwg/Umpush-Light.ttf"
    font "./nectec-tlwg/Umpush-LightOblique.ttf"
    font "./nectec-tlwg/Umpush-Oblique.ttf"
end