# This file is automatically generated.

cask "font-f0nt-ac-espressa" do
    version "1"
  
    url "https://www.f0nt.com/download/acreative/ac-espressa/AC-Espressa.zip"
    sha256 "0a5d1cbcd6e6f72adffe53db259601eaebb61f46acd8c620bffd9e4606985ed1"

    name "AC Espressa"
    homepage "https://www.f0nt.com/release/ac-espressa/"

    font "AC Espressa.ttf"
    font "__MACOSX/._AC Espressa.ttf"
 end