# This file is automatically generated.

cask "font-f0nt-kwang-md" do
    version "1"
  
    url "https://www.f0nt.com/download/kwang/4803_Kwang_MD.zip"
    sha256 "2f54b29f635ca46c6cb0270ca29388a7c2b809180fabfc8998598f8e8cfb60f1"

    name "4803_Kwang_MD"
    homepage "https://www.f0nt.com/release/4803_kwang_md/"

    font "4803_Kwang_MD.ttf"
 end