# This file is automatically generated.

cask "font-f0nt-peach-play" do
    version "1"
  
    url "https://www.f0nt.com/download/peach/peachplay.zip"
    sha256 "5d86740b40851be7e37923f07eb0fa856ba6ed3a6cba40209611c74bedd0232c"

    name "Peach Play"
    homepage "https://www.f0nt.com/release/peach-play/"

    font "PeachPlay.ttf"
 end