# This file is automatically generated.

cask "font-f0nt-blk-suphanburi" do
    version "1"
  
    url "https://www.f0nt.com/download/bangli-ko-sa-na/BLK-Suphanburi.zip"
    sha256 "9f15fda50823f1e9286a815c75b834a5b587c09d686084ed0e9783e703f859e4"

    name "BLK-Suphanburi"
    homepage "https://www.f0nt.com/release/blk-suphanburi/"

    font "BLK-Suphanburi/BLK-Suphanburi.ttf"
 end