# This file is automatically generated.

cask "font-collection-f0nt-top20" do
    version "1.0"
  
    url "https://storage.googleapis.com/codeforthailand/fonts/collection-f0nt-top-20.zip"
    sha256 "1f180840c311ea000e2619c7ce06d98d22344b0c93a70ddc7c5f4459574c7c4f"

    name "Top 20 Fonts from f0nt.com"
    homepage "https://www.f0nt.com"

        depends_on cask: "font-f0nt-sov-baanhook"
        depends_on cask: "font-f0nt-sov-apo"
        depends_on cask: "font-f0nt-abc-aschariya"
        depends_on cask: "font-f0nt-sov-tejo"
        depends_on cask: "font-f0nt-edpoonpunn"
        depends_on cask: "font-f0nt-sd-prostreet"
        depends_on cask: "font-f0nt-sov-patavi"
        depends_on cask: "font-f0nt-sov-naiklong"
        depends_on cask: "font-f0nt-uid-salmon-2019"
 end