# This file is automatically generated.

cask "font-f0nt-book-r-lux-2006" do
    version "1"
  
    url "https://www.f0nt.com/download/book/Book_R-lux.zip"
    sha256 "52ec82a7fd1d50c215c896214527d9588f7d5c85b0210641123d25e252966971"

    name "Book_R-luX [2006]"
    homepage "https://www.f0nt.com/release/book_r-lux-2006/"

    font "Book_R-luX [2006].ttf"
 end