# This file is automatically generated.

cask "font-f0nt-blk-thai-vi28" do
    version "1"
  
    url "https://www.f0nt.com/download/bangli-ko-sa-na/BLK-Thai-Vi28.zip"
    sha256 "27705deaa6a16157ec82238f02ede5c0390a0f60695d76f70a1e797e1ecdf244"

    name "BLK-Thai-Vi28"
    homepage "https://www.f0nt.com/release/blk-thai-vi28/"

    font "Thai-Vi28/BLK-Thai-Vi28.ttf"
 end