# This file is automatically generated.

cask "font-f0nt-nithan" do
    version "1"
  
    url "https://www.f0nt.com/download/zilch/nithan.zip"
    sha256 "1692edf04797975b59cecd51a9c3f68248dd5c32a97d548e23d8ce875d60b5ee"

    name "นิทาน (Nithan)"
    homepage "https://www.f0nt.com/release/nithan/"

    font "Nithan/Nithan.ttf"
 end