# This file is automatically generated.

cask "font-f0nt-book-akhanake" do
    version "1"
  
    url "https://www.f0nt.com/download/book/Book_Akhanake.zip"
    sha256 "b65b1346b64f07cc393e65b9405b5e84e672144da3d004db030a454a286ffba2"

    name "Book เอกเขนก"
    homepage "https://www.f0nt.com/release/book-akhanake/"

    font "Book Akhanake/Book_Akhanake.ttf"
 end