# This file is automatically generated.

cask "font-f0nt-fontnongnam" do
    version "1"
  
    url "https://www.f0nt.com/download/suphan06/NongNam.zip"
    sha256 "28346d650bd1a74d149676c43eec7bfba76304ea90fabdb27316228c43ff6669"

    name "FontNongnam (ฟอนต์น้องน้ำ)"
    homepage "https://www.f0nt.com/release/fontnongnam/"

    font "FONTNONGNAM.TTF"
 end