# This file is automatically generated.

cask "font-f0nt-kt-smarn" do
    version "1"
  
    url "https://www.f0nt.com/download/smarnfont/kt_smarn.zip"
    sha256 "ebb06e5cf339a6b5c38ba2aca65f3eb3c7779834d70918ae04b683d0f85bd0fa"

    name "kt_smarn"
    homepage "https://www.f0nt.com/release/kt_smarn/"

    font "kt_smarn.ttf"
    font "kt_smarnspecial.ttf"
 end