# This file is automatically generated.

cask "font-f0nt-iannnnnmtv" do
    version "1"
  
    url "https://www.f0nt.com/download/iannnnn/2005_iannnnnMTV.zip"
    sha256 "2ece8eb794e71f9477ffe8b09326e8b962cea5bbca260bb72560357bcf1afc6c"

    name "iannnnnMTV (2005)"
    homepage "https://www.f0nt.com/release/iannnnnmtv/"

    font "2005_iannnnnMTV.ttf"
 end