# This file is automatically generated.

cask "font-f0nt-bangna-new" do
    version "1"
  
    url "https://www.f0nt.com/download/wdbank/bangna-new.zip"
    sha256 "ff1cd40f2535d0f3381e3465cfe69a0d57c4d84d0854502863d768fbf577be8c"

    name "บางนา ตัดใหม่ (Bangna New)"
    homepage "https://www.f0nt.com/release/bangna-new/"

    font "bangna-new.ttf"
 end