# This file is automatically generated.

cask "font-f0nt-ts-kaewpet-np-ts-kaewpet-extra-np" do
    version "1"
  
    url "https://www.f0nt.com/download/tsfont/TS-Kaewpet-NP.zip"
    sha256 "b672256d81d289bd317f1be6ea97b1f512ad6093d8e878ea9badb0d0f8426bdb"

    name "TS-Kaewpet-NP และ TS-Kaewpet Extra-NP"
    homepage "https://www.f0nt.com/release/ts-kaewpet-np-ts-kaewpet-extra-np/"

    font "TS-Kaewpet-NP/TS-kaewpet Bold-NP.ttf"
    font "__MACOSX/TS-Kaewpet-NP/._TS-kaewpet Bold-NP.ttf"
    font "TS-Kaewpet-NP/TS-kaewPet Extra-NP.ttf"
    font "__MACOSX/TS-Kaewpet-NP/._TS-kaewPet Extra-NP.ttf"
    font "TS-Kaewpet-NP/TS-kaewpet NP.ttf"
    font "__MACOSX/TS-Kaewpet-NP/._TS-kaewpet NP.ttf"
 end