# This file is automatically generated.

cask "font-f0nt-layiji-sarangheyo" do
    version "1"
  
    url "https://www.f0nt.com/download/layiji/Layiji-sarangheyo.zip"
    sha256 "4270a08b0d59d6f405c73fa0d7306e55b4e9ff9d4a394b8eec52bcbb63d11ef4"

    name "Layiji ซารังเฮโย"
    homepage "https://www.f0nt.com/release/layiji-sarangheyo/"

    font "Layiji sarangheyo/LayijiSarangheyo.ttf"
 end